### ISSUE TITLE
Get annotation web server up to serve images with basic query

### ISSUE THREAD

**Issue by hyi** [RENCI/ncdot-road-safety#1]
- [x] Install and set up an iRODS server on dotdata.renci.org and register DOT images stored in /projects/ncdot mounted directory in the iRODS server to have a uniform way to serve images in our local development environment as well as staging and production environment. This iRODS server will be an optional component to accommodate serving data in different development, test, and production environments and can be turned on or off by a configuration flag in the annotation web server deployment.

- [x] Develop the annotation web server framework that will run in docker containers. The web server uses iRODS to serve image data but can be configured via a configuration flag later not to use iRODS as needed.

- [x] Write code to ingest the metadata exported from the Pathway services viewer into the postGIS database set up in the annotation web server framework so as to support basic geolocation based or other attribute based query to serve image data to the annotation web client.

- [x] Develop basic query endpoint response code in the annotation web server to serve data to the annotation web client via basic query.

- [x] Test and make sure it works in local development environment as well as a staging/production deployment environment, then make it available for the annotation web client development.

Refer to https://docs.google.com/presentation/d/1eF0_aeAYsI09uWiVabjcO9jlGn9Gt8cpm59hW9aHRW0/edit#slide=id.g9447e401ee_2_75 for the draft system architecture diagram.

**Comment by trel** [comment]
@hyi happy to look over the iRODS part of the architecture if that's helpful

**Comment by hyi** [comment]
Thanks @trel We will definitely reach out to you as we move along with this project for questions/advice regarding the iRODS component of the architecture. I assume you can look at the draft system architecture diagram at the google doc link above, and let us know if you see any issues with how we leverage the iRODS for now.

**Comment by trel** [comment]
I don't know enough about the use cases and requirements, so it's hard to evaluate the diagram so far.   Yes, please reach out when ready.

**Comment by hyi** [comment]
Done and closing the issue.
